### ISSUE TITLE
Error in SSR

### ISSUE THREAD

**Issue by jsulpis** [CodyJasonBennett/four#13]
Hi,
I would like to use the lib in an SSR context (Astro + Svelte), but it breaks on the server side.

**Issue:**
https://github.com/CodyJasonBennett/four/blob/05d99b3c792edc2708f47fe2876c5c210c65b616/src/WebGPURenderer.ts#L118-L119

On the server side, `_adapter` is `false` (not `null` or `undefined`), so at the next line the function `requestDevice` will be called even with the optional chaining, which throws an error.

**Solution:**
Make the `_adapter` `null` or `undefined` on the server side, so that the optional chaining works as expected:
```javascript
 const _adapter = typeof navigator !== 'undefined' ? (await navigator.gpu?.requestAdapter()) : null;
```

**Comment by CodyJasonBennett** [comment]
Which environment is this? I'll add a check in CI to mock it.

**Comment by jsulpis** [comment]
I was using Astro with node.js, but I can reproduce the issue in the browser console with the following code, so it's just a javascript error:
```javascript
const _adapter = typeof navigator === 'undefined' && { requestDevice: () => "foo" }
_adapter?.requestDevice() // Uncaught TypeError: _adapter?.requestDevice is not a function
```
