### ISSUE TITLE
[feature] custom sorting

### ISSUE THREAD

**Issue by makc** [CodyJasonBennett/four#3]
can we have [this](https://github.com/CodyJasonBennett/four/blob/main/src/WebGLRenderer.ts#L575) changed to something like `return renderList.sort(this.sortAlgo || ....)` so people could override sorting via `renderer.sortAlgo = mySuperSmartCustomSort` or Idk

**Comment by makc** [comment]
also, while at that, can we not have renderList created every time and instead have its length set to 0 [here](https://github.com/CodyJasonBennett/four/blob/main/src/WebGLRenderer.ts#L552), Im sure GC is not too happy about this

**Comment by CodyJasonBennett** [comment]
I intended for this method to be overridden in user-land via class overloads or extensions if one were to completely forgo sorting or do their own. That should still satisfy this request, although the inbuilt sorting algorithm can be further optimized to not rely on ES6 methods which do a memcpy.
