### ISSUE TITLE
question about `perspective projection matrix`

### ISSUE THREAD

**Issue by Randysheng** [CodyJasonBennett/four#4]
The perspective projection matrix in this project is 
```
[ f / aspect,   0,  0,   0, 
 0,  f,  0,  0, 
 0,  0, (far + near) * depth, -1, 
 0,  0, 2 * far * near * depth, 0
]
```

But, When I google, many answers are 
```
[ f / aspect,   0,  0,   0, 
 0,  f,  0,  0, 
 0,  0, (far + near) * depth, 2 * far * near * depth, 
 0,  0, -1, 0
]
```

so, why is that?

**Comment by CodyJasonBennett** [comment]
This project uses a right-handed coordinate system so positive Z is towards the camera as opposed to away and left handed like the other projection matrix.
