### ISSUE TITLE
OrbitControls

### ISSUE THREAD

**Issue by caramboleyo** [CodyJasonBennett/four#6]
@CodyJasonBennett do you have some kind of OrbitControls lying around?
I fugured maybe you have something you use for testing or so

**Comment by CodyJasonBennett** [comment]
The cube/transparency examples use one -- https://github.com/CodyJasonBennett/four/blob/main/examples/utils/OrbitControls.ts and I have a three.js version at https://gist.github.com/CodyJasonBennett/4c2b6f758dec7be618eafd5b3d96769a.

**Comment by caramboleyo** [comment]
The original Three.js-OrbitControls is fully compatible with four, do i understand this right?

**Comment by CodyJasonBennett** [comment]
Not quite since Four does not implement the same math methods and may deviate for conciseness/correctness since it targets WebGL/WebGPU. It won't take much to mend if you want to use that instead.

**Comment by caramboleyo** [comment]
No, my next question just would have been if that means the gltf loader would work too :)
